spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 53851653672-c73eerjorhm6sst0a0r3julu7iuo3405.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8090/login/oauth2/code/google"
            scope:
              - openid
              - email
              - profile
        provider:
          custom-google:
            issuer-uri: https://accounts.google.com #when this discovery endpoint is not found during a startup, our server won't start.